[project]
name = "hexlet-ci-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mikhail", email = "MikhaelLobanov770@yandex.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
hexlet-ci-train = "hexlet_ci_train:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
